Homework 1
================
Zhongqi Yue

This is my solution to HW1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ──────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame with the specified elements.

``` r
prob1_df =
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a","b","c","d","e","f","g","h","i","j"),
    factor_vec = factor(c("low","low","low","mod","mod","mod","mod","high","high","high"))
  )
```

Take the mean of each variable in my data frame.

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.2864492

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.4

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the mean of numbers and logical but not character and factor.

``` r
as.numeric(pull(prob1_df, samp))
```

    ##  [1] -0.229874690 -0.162164316 -0.717657748 -1.234424561  0.341642505
    ##  [6]  0.859391217 -1.063833275 -0.734485446  0.006667605  0.070247058

``` r
as.numeric(pull(prob1_df, samp_gt_0))
```

    ##  [1] 0 0 0 0 1 1 0 0 1 1

``` r
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

“as.numeric” works for the random sample and logical vector but not
character and factor, which explains why I cannot take the mean for
them.

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df,samp)
```

    ##  [1] 0.000000000 0.000000000 0.000000000 0.000000000 0.341642505 0.859391217
    ##  [7] 0.000000000 0.000000000 0.006667605 0.070247058

``` r
as.factor(pull(prob1_df, samp_gt_0)) 
```

    ##  [1] FALSE FALSE FALSE FALSE TRUE  TRUE  FALSE FALSE TRUE  TRUE 
    ## Levels: FALSE TRUE

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df,samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) 
```

    ##  [1] 1 1 1 1 2 2 1 1 2 2

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df,samp)
```

    ##  [1] -0.22987469 -0.16216432 -0.71765775 -1.23442456  0.68328501  1.71878243
    ##  [7] -1.06383327 -0.73448545  0.01333521  0.14049412

I can multiply the random sample by the result to the logical vector
which is converted to numeric but not to factor. But if I convert the
logical vector to a factor and then convert the result to numeric, I can
multiply the random sample by the result.

## Problem 2

``` r
data("penguins", package = "palmerpenguins")
```

#### The short description of the data set

``` r
prob2_df = (force(penguins))
as.numeric(pull(prob2_df, species))
```

    ##   [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ##  [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ##  [75] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ## [112] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ## [149] 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
    ## [186] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
    ## [223] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
    ## [260] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    ## [297] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    ## [334] 2 2 2 2 2 2 2 2 2 2 2

``` r
as.numeric(pull(prob2_df, island))
```

    ##   [1] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2
    ##  [38] 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3
    ##  [75] 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1
    ## [112] 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    ## [149] 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ## [186] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ## [223] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    ## [260] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    ## [297] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    ## [334] 2 2 2 2 2 2 2 2 2 2 2

``` r
nrow(prob2_df)
```

    ## [1] 344

``` r
ncol(prob2_df)
```

    ## [1] 8

``` r
mean(pull(prob2_df, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

This data set has 344 observations and 8 variables which are species,
island, bill\_length\_mm, bill\_depth\_mm, flipper\_length\_mm,
body\_mass\_g, sex and year. For species, it has 152 Adelie, 52 of which
are on Torgersen island, 44 of which are on Biscoe island, 56 of which
are on Dream island; 124 Gentoo, all of which are on Biscoe island; and
68 Chinstrap, all of which are on Dream island. The data set has 334
rows and 8 columns. Additionally, the mean flipper length is 200.9152
mm.

#### The scatterplot of flipper\_length\_mm (y) vs bill\_length\_mm (x)

``` r
ggplot(prob2_df, aes(y = flipper_length_mm, x = bill_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_zy2442_files/figure-gfm/prob2_plot-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 4)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
